### ISSUE TITLE
pygame dependency not checked in installer

### ISSUE THREAD

**Issue by sgarriga** [ssilverm/piplay-installer#3]
Just used the installer with a fresh Raspian Jessie Lite image. Everything ran clean on the install, but I got an error about a missing pygame module when I tried to start piplay....

sudo apt-get install python-pygame

... fixed it. Given all the other dependencies checked maybe this one should be added?

**Comment by mholgatem** [comment]
yeah, it probably got left out since it comes pre-installed on other distros. I went ahead and updated the installer, so it should be good now.
